package Daje::Workflow::GenerateSQL::Base::Common;
use Mojo::Base -base, -signatures;

has 'json' ;
has 'template' ;
has 'sql' ;
has 'index' => 0;
has 'version' ;
has 'error';

sub shift_section ($array) {
    my $result = {};
    my $test = ref $array;
    if (ref $array eq 'ARRAY') {
        $result = shift(@{$array});
    }
    return $result;
}
sub set_sql($self, $sqlin) {
    $self->sql($sqlin);
}


1;









#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

lib::Daje::Generate::Sql::Base::Common - lib::Daje::Generate::Sql::Base::Common


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<feature> 

L<v5.40> 


=head1 METHODS


=cut

